SHOW ENGINES;

CREATE TABLE CONTA_BANCARIA
(
	CODIGO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT, -- Código interno (PK)
	TITULAR VARCHAR(32) NOT NULL, -- Nome do titular da conta
	SALDO DOUBLE NOT NULL, -- Representa o saldo da conta
	PRIMARY KEY(CODIGO) -- Define o campo CODIGO como PK (Primary Key)
) ENGINE = InnoDB;

INSERT INTO CONTA_BANCARIA VALUES (1, 'André', 213);
INSERT INTO CONTA_BANCARIA VALUES (2, 'Diogo', 489);
INSERT INTO CONTA_BANCARIA VALUES (3, 'Rafael', 568);
INSERT INTO CONTA_BANCARIA VALUES (4, 'Carlos', 712);
INSERT INTO CONTA_BANCARIA VALUES (5, 'Peter', -38);

SET SQL_SAFE_UPDATES = 0;

start transaction;
UPDATE CONTA_BANCARIA SET saldo = saldo*1.03 WHERE SALDO > 0;
commit;

SELECT * FROM CONTA_BANCARIA;
